---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/en
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/en/training
  label: Training
  create: all
  match: "**/*"
- type: directory
  path: content/en/partners
  label: Partners
  create: all
  match: "**/*"
- type: directory
  path: content/en/includes
  label: Includes
  create: all
  match: "**/*"
- type: directory
  path: content/en/examples
  label: Examples
  create: all
  match: "**/*"
- type: directory
  path: content/en/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content/en/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/en/case-studies
  label: Case studies
  create: all
  match: "**/*"
- type: directory
  path: content/en/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/en/_common-resources
  label: Common resources
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
